document.getElementById('tableid').innerHTML=
`<table border="1">
<tr>
<th>Name</th>
<th>Age</th>
<th>Address</th>
<th>DOB</th>
<th>E-mail</th>
<th>Gender</th>
</tr>
<tr>
<td>Simran</td>
<td>22</td>
<td>Abc</td>
<td>26/07/97</td>
<td>simran2014goyal@gmail.com</td>
<td>female</td>
</tr>
<tr>
<td>luqhmaan</td>
<td>22</td>
<td>def</td>
<td>3/08/96</td>
<td>luqhmaan34@gmail.com</td>
<td>Male</td>
</tr>
<tr>
<td>ranu</td>
<td>21</td>
<td>ghi</td>
<td>2/07/97</td>
<td>rane@gmail.com</td>
<td>female</td>
</tr>
<tr>
<td>deepti</td>
<td>21</td>
<td>jkl</td>
<td>31/10/97</td>
<td>deepti@gmail.com</td>
<td>female</td>
</tr>
</table>`;